const data = [
  {
    id: 1103,
    group_name: "9 группа",
    classroom: 24,
    classroom_name: "609",
    teacher_name: "Азаров А. И.",
    subgroup: null,
    subgroup_name: null,
    subject: "Численные методы",
    availability: {
      type: "after",
      date: {
        day: 31,
        month: 3,
      },
    },
    content: "26.05 отработка за 28.04",
    timestart: 780,
    timeend: 860,
    type: "л",
    weekday: "MONDAY",
  },
  {
    id: 1104,
    group_name: "9 группа",
    classroom: 38,
    classroom_name: "353",
    teacher_name: "Михейчик А. Д.",
    subgroup: null,
    subgroup_name: null,
    subject: "Теория вероятностей и математическая статистика",
    availability: null,
    content: null,
    timestart: 870,
    timeend: 950,
    type: "п",
    weekday: "MONDAY",
  },
  {
    id: 1105,
    group_name: "9 группа",
    classroom: 5,
    classroom_name: "339",
    teacher_name: "Бедрицкий А. С.",
    subgroup: null,
    subgroup_name: null,
    subject: "Функциональный анализ",
    availability: null,
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "MONDAY",
  },
  {
    id: 1106,
    group_name: "9 группа",
    classroom: 25,
    classroom_name: "242",
    teacher_name: "Архипенко О. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Численные методы",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "MONDAY",
  },
  {
    id: 1107,
    group_name: "9 группа",
    classroom: 20,
    classroom_name: "405",
    teacher_name: "Азаров А. И.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Численные методы",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "MONDAY",
  },
  {
    id: 1109,
    group_name: "9 группа",
    classroom: 28,
    classroom_name: "349",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: null,
    content: "18.03; 25.03; 01.04 — 29.04; 06.05; 13.05",
    timestart: 780,
    timeend: 860,
    type: "п",
    weekday: "TUESDAY",
  },
  {
    id: 1110,
    group_name: "9 группа",
    classroom: 4,
    classroom_name: "606",
    teacher_name: "Докукова Н. А.",
    subgroup: null,
    subgroup_name: null,
    subject: "Теоретическая механика",
    availability: null,
    content: null,
    timestart: 870,
    timeend: 950,
    type: "л",
    weekday: "TUESDAY",
  },
  {
    id: 1111,
    group_name: "9 группа",
    classroom: 19,
    classroom_name: "347",
    teacher_name: "Авдейчик Е. В.",
    subgroup: null,
    subgroup_name: null,
    subject: "Теоретическая механика",
    availability: null,
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "TUESDAY",
  },
  {
    id: 1112,
    group_name: "9 группа",
    classroom: 4,
    classroom_name: "606",
    teacher_name: "Перез Чернов А. Х.",
    subgroup: null,
    subgroup_name: null,
    subject: "Системная архитектура и управление проектами",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "л",
    weekday: "TUESDAY",
  },
  {
    id: 1113,
    group_name: "9 группа",
    classroom: 6,
    classroom_name: "340",
    teacher_name: "Короткевич Л. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы предпринимательской деятельности",
    availability: {
      type: "in_range",
      from: {
        day: 1,
        month: 4,
      },
      to: {
        day: 29,
        month: 4,
      },
    },
    content: null,
    timestart: 1150,
    timeend: 1230,
    type: "п",
    weekday: "TUESDAY",
  },
  {
    id: 1114,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "except",
      dates: [
        {
          day: 23,
          month: 4,
        },
        {
          day: 30,
          month: 4,
        },
      ],
    },
    content: null,
    timestart: 870,
    timeend: 950,
    type: "л",
    weekday: "WEDNESDAY",
  },
  {
    id: 1115,
    group_name: "9 группа",
    classroom: 4,
    classroom_name: "606",
    teacher_name: "Перез Чернов А. Х.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы облачных технологий",
    availability: null,
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "л",
    weekday: "WEDNESDAY",
  },
  {
    id: 1116,
    group_name: "9 группа",
    classroom: 3,
    classroom_name: "404",
    teacher_name: "Филимонов Д. В.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Алгоритмы и структуры данных",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "WEDNESDAY",
  },
  {
    id: 1117,
    group_name: "9 группа",
    classroom: 20,
    classroom_name: "405",
    teacher_name: "Перез Чернов А. Х.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Основы облачных технологий",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "WEDNESDAY",
  },
  {
    id: 1118,
    group_name: "9 группа",
    classroom: 3,
    classroom_name: "404",
    teacher_name: "Филимонов Д. В.",
    subgroup: null,
    subgroup_name: null,
    subject: "Алгоритмы и структуры данных",
    availability: {
      type: "odd_week",
    },
    content: null,
    timestart: 1150,
    timeend: 1230,
    type: "л",
    weekday: "WEDNESDAY",
  },
  {
    id: 1119,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "only",
      dates: [
        {
          day: 14,
          month: 5,
        },
        {
          day: 28,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 1150,
    timeend: 1230,
    type: "л",
    weekday: "WEDNESDAY",
  },
  {
    id: 1120,
    group_name: "9 группа",
    classroom: 37,
    classroom_name: "351",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: {
      type: "only",
      dates: [
        {
          day: 1,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 585,
    timeend: 665,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1121,
    group_name: "9 группа",
    classroom: 18,
    classroom_name: "255",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: {
      type: "only",
      dates: [
        {
          day: 24,
          month: 4,
        },
        {
          day: 8,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 675,
    timeend: 755,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1122,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "odd_week",
    },
    content: null,
    timestart: 780,
    timeend: 860,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1122,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "except",
      dates: [
        {
          day: 24,
          month: 4,
        },
      ],
    },
    content: null,
    timestart: 780,
    timeend: 860,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1123,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "even_week",
    },
    content: null,
    timestart: 780,
    timeend: 860,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1124,
    group_name: "9 группа",
    classroom: 4,
    classroom_name: "606",
    teacher_name: "Штин С. Л.",
    subgroup: null,
    subgroup_name: null,
    subject: "Функциональный анализ",
    availability: null,
    content: null,
    timestart: 870,
    timeend: 950,
    type: "л",
    weekday: "THURSDAY",
  },
  {
    id: 1125,
    group_name: "9 группа",
    classroom: 3,
    classroom_name: "404",
    teacher_name: "Перез Чернов А. Х.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Основы облачных технологий",
    availability: null,
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1126,
    group_name: "9 группа",
    classroom: 20,
    classroom_name: "405",
    teacher_name: "Вельченко С. А.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Алгоритмы и структуры данных",
    availability: {
      type: "except",
      dates: [
        {
          day: 24,
          month: 4,
        },
      ],
    },
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1127,
    group_name: "9 группа",
    classroom: 7,
    classroom_name: "341",
    teacher_name: "Кремень Ю. А.",
    subgroup: null,
    subgroup_name: null,
    subject: "Информ/кураторский час",
    availability: null,
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: null,
    weekday: "THURSDAY",
  },
  {
    id: 1128,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Алгоритмы и структуры данных",
    availability: {
      type: "only",
      dates: [
        {
          day: 8,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "THURSDAY",
  },
  {
    id: 1130,
    group_name: "9 группа",
    classroom: 24,
    classroom_name: "609",
    teacher_name: "Спасков С. А.",
    subgroup: null,
    subgroup_name: null,
    subject: "Теория вероятностей и математическая статистика",
    availability: null,
    content: null,
    timestart: 780,
    timeend: 860,
    type: "л",
    weekday: "FRIDAY",
  },
  {
    id: 1131,
    group_name: "9 группа",
    classroom: 19,
    classroom_name: "347",
    teacher_name: "Муравицкая Е. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Белорусский язык",
    availability: {
      type: "except",
      dates: [
        {
          day: 18,
          month: 4,
        },
      ],
    },
    content: "профессиональная лексика",
    timestart: 870,
    timeend: 950,
    type: "п",
    weekday: "FRIDAY",
  },
  {
    id: 1132,
    group_name: "9 группа",
    classroom: 22,
    classroom_name: "407",
    teacher_name: "Кирвель П. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Системная архитектура и управление проектами",
    availability: {
      type: "odd_week",
    },
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "FRIDAY",
  },
  {
    id: 1133,
    group_name: "9 группа",
    classroom: 22,
    classroom_name: "407",
    teacher_name: "Кирвель П. А.",
    subgroup: 121,
    subgroup_name: "б",
    subject: "Системная архитектура и управление проектами",
    availability: {
      type: "even_week",
    },
    content: null,
    timestart: 960,
    timeend: 1040,
    type: "п",
    weekday: "FRIDAY",
  },
  {
    id: 1134,
    group_name: "9 группа",
    classroom: 5,
    classroom_name: "339",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: {
      type: "only",
      dates: [
        {
          day: 9,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 1060,
    timeend: 1140,
    type: "п",
    weekday: "FRIDAY",
  },
  {
    id: 1135,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "odd_week",
    },
    content: null,
    timestart: 495,
    timeend: 575,
    type: "п",
    weekday: "SATURDAY",
  },
  {
    id: 1135,
    group_name: "9 группа",
    classroom: 21,
    classroom_name: "52 цоколь",
    teacher_name: "Вельченко С. А.",
    subgroup: 120,
    subgroup_name: "а",
    subject: "Основы виртуальной и дополненной реальностей",
    availability: {
      type: "only",
      dates: [
        {
          day: 17,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 495,
    timeend: 575,
    type: "п",
    weekday: "SATURDAY",
  },
  {
    id: 1136,
    group_name: "9 группа",
    classroom: 4,
    classroom_name: "606",
    teacher_name: "Короткевич Л. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы предпринимательской деятельности",
    availability: {
      type: "in_range",
      from: {
        day: 15,
        month: 3,
      },
      to: {
        day: 3,
        month: 5,
      },
    },
    content: null,
    timestart: 585,
    timeend: 665,
    type: "л",
    weekday: "SATURDAY",
  },
  {
    id: 1137,
    group_name: "9 группа",
    classroom: 24,
    classroom_name: "609",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: {
      type: "in_range",
      from: {
        day: 15,
        month: 3,
      },
      to: {
        day: 17,
        month: 5,
      },
    },
    content: null,
    timestart: 675,
    timeend: 755,
    type: "л",
    weekday: "SATURDAY",
  },
  {
    id: 1138,
    group_name: "9 группа",
    classroom: 24,
    classroom_name: "609",
    teacher_name: "Хлус А. М.",
    subgroup: null,
    subgroup_name: null,
    subject: "Основы права",
    availability: {
      type: "in_range",
      from: {
        day: 15,
        month: 3,
      },
      to: {
        day: 5,
        month: 4,
      },
    },
    content: null,
    timestart: 780,
    timeend: 860,
    type: "л",
    weekday: "SATURDAY",
  },
  {
    id: 1108,
    group_name: "9 группа",
    classroom: null,
    classroom_name: null,
    teacher_name: null,
    subgroup: null,
    subgroup_name: null,
    subject: "Физическая культура",
    availability: {
      type: "only",
      dates: [
        {
          day: 6,
          month: 5,
        },
      ],
    },
    content: null,
    timestart: 590,
    timeend: 670,
    type: null,
    weekday: "MONDAY",
  },
  {
    id: 1129,
    group_name: "9 группа",
    classroom: null,
    classroom_name: null,
    teacher_name: null,
    subgroup: null,
    subgroup_name: null,
    subject: "Физическая культура",
    availability: null,
    content: null,
    timestart: 660,
    timeend: 740,
    type: null,
    weekday: "FRIDAY",
  },
  {
    id: 1102,
    group_name: "9 группа",
    classroom: null,
    classroom_name: null,
    teacher_name: null,
    subgroup: null,
    subgroup_name: null,
    subject: "Физическая культура",
    availability: null,
    content: null,
    timestart: 660,
    timeend: 740,
    type: null,
    weekday: "MONDAY",
  },
]

const mapped = data.reduce((acc, v) => {
  const arr = acc[v.id] || []
  acc[v.id] = [...arr, v]
  return acc
}, {})

const result = Object.values(mapped).map((l) =>
  l.reduce((acc, v) => {
    const availability = acc.availability || []
    const content = acc.content || []
    const copy = acc == {} || v

    if (v.availability !== null) {
      copy.availability = [...availability, v.availability]
    }

    if (v.content !== null) {
      copy.content = [...content, v.content]
    }

    return copy
  }, {})
)

console.log(JSON.stringify(result, null, 4))
